"""add job criteria syllabus questions

Revision ID: b8a2cff7b76f
Revises: 7a90c7f81a48
Create Date: 2026-09-22 12:56:37.872555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a2cff7b76f'
down_revision: Union[str, Sequence[str], None] = '7a90c7f81a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('criterion_text', sa.Text(), nullable=False),
    sa.Column('criterion_type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_criteria_id'), 'job_criteria', ['id'], unique=False)
    op.create_table('syllabus_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('competency', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_items_id'), 'syllabus_items', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('syllabus_item_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('competency', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('is_follow_up_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['syllabus_item_id'], ['syllabus_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_syllabus_items_id'), table_name='syllabus_items')
    op.drop_table('syllabus_items')
    op.drop_index(op.f('ix_job_criteria_id'), table_name='job_criteria')
    op.drop_table('job_criteria')
    # ### end Alembic commands ###
